services:
  l4d2:
    container_name: l4d2
    build: .
    restart: unless-stopped
    network_mode: host
    environment:
      - HOSTNAME=
      - REGION=0
      - STEAM_GROUP=
      - STEAM_GROUP_EXCLUSIVE=
      - HOST_CONTENT=
      - MOTD_CONTENT=
      - MOTD=1
      - IPADDRESS=
      - PORT=27015
      - RCON_PASSWORD=
    volumes:
      - ./addons:/addons/
      - ./cfg:/cfg
      - ./scripts:/home/steam/l4d2/left4dead2/scripts
      